#---------------------------------#
#  Build Script                   #
#---------------------------------#

build_script:
  - ps: .\build.ps1 --bootstrap
  - ps: .\build.ps1 -Target ContinuousIntegration

#---------------------------------#
# Tests
#---------------------------------#

test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- Source\packages -> Source\**\packages.config
- tools -> recipe.cake, tools\packages.config
