Vagrant.configure("2") do |config|
  config.vm.box = "win2012r2x64"

  config.vm.provider :virtualbox do |v, override|
    v.gui = false
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
    v.customize ["modifyvm", :id, "--vram", 32]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--audio", "none"]
    v.customize ["modifyvm", :id, "--clipboard", "disabled"]
    v.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    v.customize ["modifyvm", :id, "--usb", "off"]
    v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
  end

  config.windows.halt_timeout = 20
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.guest = :windows
  # https://www.vagrantup.com/blog/feature-preview-vagrant-1-6-windows.html

  if Vagrant::VERSION >= '1.6.0'
    config.vm.communicator = "winrm"
  end

  config.vm.synced_folder "files", "/ProgramData/chocolatey/.chocolatey"
  config.vm.synced_folder "choco_logs", "/ProgramData/chocolatey/logs"

  # Port forward WinRM / RDP
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
  # Port forward SSH (ssh is forwarded by default in most versions of Vagrant, but be sure)
  #  It's not necessary if you are not using SSH, but it doesn't hurt anything to have it
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

  config.vm.provision :shell, :path => "shell/VagrantAction.ps1", :powershell_elevated_interactive => true
end